# Generated by Django 4.2.16 on 2024-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=255)),
                ("artist_name", models.CharField(max_length=255)),
                ("recommended_songs", models.JSONField()),
            ],
        ),
    ]
