# Generated by Django 4.2.16 on 2024-10-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="artist_name",
            new_name="referenceArtist",
        ),
        migrations.RenameField(
            model_name="recommendation",
            old_name="song_name",
            new_name="referenceTrack",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="badges",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="toggles",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="recommended_songs",
            field=models.JSONField(null=True),
        ),
    ]
