# Generated by Django 4.2.16 on 2024-10-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clustering", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clusters",
            new_name="Cluster",
        ),
    ]
