# Generated by Django 4.2.16 on 2024-10-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clustering", "0002_rename_clusters_cluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="samplingSize",
            field=models.CharField(default="all", max_length=255),
            preserve_default=False,
        ),
    ]
